# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170709_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='teacher/%Y/m', verbose_name='头像'),
        ),
    ]
