# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.CharField(default=0, max_length=10, verbose_name='课程时长'),
        ),
    ]
