# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170806_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否首页轮播显示'),
        ),
    ]
